### ISSUE TITLE
waitFor more than html to exists

### ISSUE THREAD

**Issue by ryanto** [kellyselden/ember-wait-for-test-helper#2]
Great addon, we're using something similar in one of our code bases that I want to share/open source. Our `waitFor` looks almost identical to yours.

One thing is we need to sometimes wait for more than HTML elements to exist. In our system `waitFor` takes a function and when that function returns true the promise fulfills.

Here's some code.

```javascript
// ember-wait-for-test-helper
waitFor('.element-to-exist');

// would be the same as waitFor that takes function
waitFor(selectorToExist('.element-to-exist'));

// This opens the door to composition, so you can do things like...

waitFor(videoToBePlayable('.video'));

waitFor(() => {
  let result = ... // check for some value
  return result;
});
```

I think composition gives you the ability to write more powerful waiters (for lack of a better word). However, this would be a breaking API change so I wanted to get your thoughts.

**Comment by kellyselden** [comment]
First of all, great idea. Second, we could make it additive API if the `waitFor` function took either a string selector, or a function.

**Comment by ryanto** [comment]
Yup was thinking the same thing to keep API the same. I'll PR this

**Comment by kellyselden** [comment]
Added in #3
