### ISSUE TITLE
Infinite wait for

### ISSUE THREAD

**Issue by ro0gr** [kellyselden/ember-wait-for-test-helper#4]
Currently if a searched element will never appear(due to bug) `wait-for` keeps polling the DOM even when test has reached a timeout.

Reproduction:
https://ember-twiddle.com/e0317e387d4811bdfc5f422d925e59de?openFiles=tests.helpers.wait-for.js%2C
In the twiddle I've copy-pasted `wait-for` source and slightly modified it to update QUnit Header Title on each `wait-for` iteration. As a result the header is updated even when the test timeout happened.

I've made a quick research on how to stop this infinite loop and can't find any valid way to solve it.

Any ideas?

**Comment by kellyselden** [comment]
The API here could definitely use a timeout option. I think that would solve your issue.

**Comment by ro0gr** [comment]
I think that timeout is not the most ergonomic option here. 
Specifying timeouts for each `waitFor` is not very scalable as for me.

It would be great to have a built-in way to stop `waitFor` when the test is over.

**Comment by ro0gr** [comment]
I mean an ideal world of course :)

**Comment by kellyselden** [comment]
This should be good now after #12. Reopen if not.
